build: all

all: repng.cc

repng.cc:
	curl -L https://snapshot.debian.org/archive/debian/20120101T000000Z/pool/main/a/advancecomp/advancecomp_1.15.orig.tar.gz | tar xz --strip-components=1

clean:

install:

.PHONY: build all install clean
